package org.cis1200;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.time.Duration;

import java.io.BufferedReader;
import java.io.StringReader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/** Tests for TwitterBot class */
class TwitterBotTest {

    /*
     * The below test cases test whether your TwitterBot class itself is written
     * correctly. To generate a tweet of specific content, make a desiredTweet list
     * containing the words you want to appear in the tweet. Then, call
     * fixDistribution on desiredTweet. This should make your Twitter bot generate
     * the desired tweet as a string when you call generateTweet with the length of
     * your tweet content (not including punctuations).
     *
     * These tests operate very similarly to our MarkovChain tests in its use of
     * `fixDistribution`, so make sure you know how to test MarkovChain before
     * testing this!
     */
    @Test
    void simpleTwitterBotShortTest() {
        List<String> desiredTweet = new ArrayList<>(
                Arrays.asList(
                        "hello", "cis1200", "world", "!"
                )
        );
        String words = "0, simple test.\n"
                + "1, hello cis1200 world!\n"
                + "2, this is amazing.";
        StringReader sr = new StringReader(words);
        BufferedReader br = new BufferedReader(sr);
        TwitterBot t = new TwitterBot(br, 1);
        t.fixDistribution(desiredTweet);

        String expected = "hello cis1200 world!";
        String actual = t.generateTweet(3);
        Assertions.assertEquals(expected, actual, "");
    }

    @Test
    void simpleTwitterBotLongTest() {
        List<String> desiredTweet = new ArrayList<>(
                Arrays.asList(
                        "this", "comes", "from", "data", "with", "no", "duplicate", "words", ".",
                        "the", "end", "should", "come", "."
                )
        );
        String words = "0, The end should come here.\n"
                + "1, This comes from data with no duplicate words!";
        StringReader sr = new StringReader(words);
        BufferedReader br = new BufferedReader(sr);
        TwitterBot t = new TwitterBot(br, 1);
        t.fixDistribution(desiredTweet);

        String expected = "this comes from data with no duplicate words. the end should come.";
        String actual = TweetParser.replacePunctuation(t.generateTweet(12));
        Assertions.assertEquals(expected, actual, "");
    }

    /*
     * This is the empty file test case.
     *
     * When your CSV file is empty, your program should create an empty MarkovChain.
     * An empty tweet should be generated by your bot.
     * No exceptions should be thrown and your program should not go into an
     * infinite loop!
     */
    @Test
    void emptyFileCreatesEmptyTweet() {
        // Checks that your program does not go into an infinite loop
        Assertions.assertTimeoutPreemptively(
                Duration.ofSeconds(10L), () -> {
                    // No exceptions are thrown if file is empty
                    BufferedReader br = FileLineIterator.fileToReader("./files/empty.csv");
                    TwitterBot tb = new TwitterBot(
                            br, 2
                    );
                    // Checks that the bot creates an empty tweet
                    Assertions.assertEquals(0, tb.generateTweet(10).length(), "");
                }
        );
    }

    /* **** ****** **** WRITE YOUR TESTS BELOW THIS LINE **** ****** **** */
    // Note: make sure to test for punctuations using `isPunctuated`.
    @Test
    void simpleTwitterBotEmptyTest() {
        List<String> desiredTweet = new ArrayList<>(
                Arrays.asList(
                        "this", "comes", "from", "data", "with", "no", "duplicate", "words", ".",
                        "the", "end", "should", "come", "."
                )
        );
        String words = "0, The end should come here.\n"
                + "1, This comes from data with no duplicate words!";
        StringReader sr = new StringReader(words);
        BufferedReader br = new BufferedReader(sr);
        TwitterBot t = new TwitterBot(br, 1);
        t.fixDistribution(desiredTweet);

        String expected = "";
        String actual = TweetParser.replacePunctuation(t.generateTweet(0));
        Assertions.assertEquals(expected, actual, "");
    }

    @Test
    void simpleTwitterBotNegativeTest() {
        List<String> desiredTweet = new ArrayList<>(
                Arrays.asList(
                        "this", "comes", "from", "data", "with", "no", "duplicate", "words", ".",
                        "the", "end", "should", "come", "."
                )
        );
        String words = "0, The end should come here.\n"
                + "1, This comes from data with no duplicate words!";
        StringReader sr = new StringReader(words);
        BufferedReader br = new BufferedReader(sr);
        TwitterBot t = new TwitterBot(br, 1);
        t.fixDistribution(desiredTweet);

        try {
            String expected = "";
            String actual = TweetParser.replacePunctuation(t.generateTweet(-1));
            Assertions.assertEquals(expected, actual, "");
        } catch (IllegalArgumentException e) {
            return;
        }
        Assertions.fail("");
    }

    @Test
    void writeStringsToFileTest() {
        // output of tests to make sure they pass
        List<String> stringsToWrite = new ArrayList<>();
        stringsToWrite.add("test1");
        stringsToWrite.add("test2");
        TwitterBot.writeStringsToFile(stringsToWrite, "files/writestringstofiletest.csv", false);
    }
}
